import {test} from 'node:test';
import assert from 'node:assert/strict';
import {parse,print} from '../packages/language/parser.ts';
import {fromText,canonical,decode,semanticId,fromSpanish,toSpanish} from '../packages/semantic/vsr.ts';
import {MemoryStore,defaultScope} from '../packages/memory/store.ts';
import {Peer,message,negotiate} from '../packages/protocol/protocol.ts';
import {ByteTokenizer,optimize,netPercent} from '../packages/codec/optimizer.ts';
import {processMessage} from '../packages/runtime/runtime.ts';
test('roundtrip canónico y literal exacto',()=>{const text='seq(sen(ri("x\\n\\\"y")),pro(nu(dar(ri("original"),agn("trash")))))';const v=fromText(text);assert.equal(print(parse(print(v.root))),text);assert.equal(semanticId(decode(canonical(v))),semanticId(v))});
test('rechaza raíz, aridad, ambigüedad y basura',()=>{for(const x of ['foo("a")','sel("a")','dar(ri("a"))','nu()','sen(ri("a"),ri("b"))','sen(ri("a")) trailing','sen(ri("a",))'])assert.throws(()=>fromText(x))});
test('restricción negativa con alcance explícito y falla de traducción libre',()=>{const v=fromSpanish('Analiza el error "1" y no elimines los archivos originales.');assert.match(print(v.root),/pro\(del\(ri/);assert.throws(()=>fromSpanish('Borrá todos los archivos'))});
test('referencia contextual sin resolver',()=>{assert.throws(()=>fromText('sel(ri("faltante"))',undefined,new Set()));assert.doesNotThrow(()=>fromText('sel(ri("ok"))',undefined,new Set(['ok'])))});
test('persistencia, aislamiento, conflicto e invalidación',()=>{const s=new MemoryStore(':memory:');const a=s.put('m1',defaultScope,'project','literal','user');assert.equal(s.getContent(a.hash),'literal');assert.throws(()=>s.put('m1',defaultScope,'project','nuevo','user',0));s.put('m1',defaultScope,'project','nuevo','user',1);assert.equal(s.retrieve(defaultScope).length,1);assert.equal(s.retrieve({...defaultScope,project:'otro'}).length,0);s.invalidate('m1',defaultScope,2);assert.equal(s.retrieve(defaultScope).length,0);s.close()});
test('protocolo: negociación, integridad, destino, recuperación y duplicado',()=>{const a=new MemoryStore(':memory:'),b=new MemoryStore(':memory:');const caps={versions:['0.1'],dictionaries:['0.1'],encodings:['veliq-text','reference','natural'] as ('veliq-text'|'reference'|'natural')[],referenceRecovery:true,maxPayload:100};const x=new Peer('a',a,caps),y=new Peer('b',b,caps);assert.equal(negotiate(caps,caps),'veliq-text');const hash=a.putContent('contenido');const e=message({session_id:'s',source:'a',destination:'b',message_type:'TASK',encoding:'reference',payload:'',references:[hash],constraints:['pro(del(...))']});assert.equal(y.receive(e,x),'contenido');assert.equal(y.receive(e,x),'duplicado');assert.throws(()=>y.receive({...e,message_id:'nuevo'},x));assert.throws(()=>y.receive({...e,destination:'otro'},x));a.close();b.close()});
test('observe no altera y hybrid cae si no hay beneficio; sobrecosto contabilizado',()=>{const s=new MemoryStore(':memory:');const original='Analiza el error "1" y no elimines los archivos originales.';const d=processMessage(original,s).decision;assert.equal(d.output,original);assert.equal(s.metrics().length,1);const h=optimize(original,fromSpanish(original),new ByteTokenizer(),'hybrid','diccionario');assert.equal(h.strategy,'natural');assert.ok(netPercent(h)<0);s.close()});
test('mensaje fuente alterada no se optimiza',()=>{const v=fromSpanish('Analiza el error "1" y no elimines los archivos originales.');assert.equal(optimize('otra frase',v,new ByteTokenizer(),'native').strategy,'natural')});

test('VSR adulterada no reutiliza español original ni optimiza',()=>{const original='Analiza el error \"1\" y no elimines los archivos originales.';const v=fromSpanish(original);v.root=fromText('del(ri(\"archivos:originales\"))').root;assert.notEqual(toSpanish(v),original);assert.equal(optimize(original,v,new ByteTokenizer(),'native').strategy,'natural')});
