import {test} from 'node:test';
import assert from 'node:assert/strict';
import {MemoryStore} from '../packages/memory/store.ts';
import {startServer} from '../apps/gateway/server.ts';
test('Studio sirve C3 y observaciones de uso diario sin inventar ahorro',async()=>{
 const store=new MemoryStore(':memory:'),server=startServer(store,0);await new Promise<void>(resolve=>server.on('listening',resolve));
 try{const port=(server.address() as {port:number}).port,url=`http://127.0.0.1:${port}`;
  const response=await fetch(url+'/api/explore',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({text:'Analyze error "case-001", fix it, and verify tests "case-001".',language:'en'})});
  const data=await response.json();assert.equal(response.status,200);assert.equal(data.c3,'case-001 sen error nar error sel tests');
  const status=await (await fetch(url+'/api/status')).json();assert.equal(status.observations.savedBytes,0);assert.equal(status.observations.countKind,'local-bytes');
  const report=await (await fetch(url+'/api/research/harness')).json();for(const item of report.results){const instructions=item.byCategory['agent-instruction'];assert.equal(instructions.c3SupportedCases,800);assert.ok(instructions.c3IncrementalVsConventionalPercent>=35);assert.equal(instructions.c3PerCallIncrementalPercent,0)}
 }finally{server.close();store.close()}
});
test('dashboard refleja medición real y rechaza plantilla desconocida',async()=>{const store=new MemoryStore(':memory:');const server=startServer(store,0);await new Promise<void>(resolve=>server.on('listening',resolve));try{const port=(server.address() as {port:number}).port;const url=`http://127.0.0.1:${port}`;const r=await fetch(url+'/api/explore',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({text:'Analiza el error "1" y no elimines los archivos originales.'})});assert.equal(r.status,200);const data=await r.json();assert.match(data.text,/pro\(del/);assert.match(data.compact,/pro\{del/);const en=await fetch(url+'/api/explore',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({text:'Analyze error "1" and do not delete the original files.',language:'en'})});assert.equal(en.status,200);assert.match((await en.json()).natural,/Analyze error/);const report=await (await fetch(url+'/api/research/multilingual')).json();assert.equal(report.summary.length,20);assert.equal(report.summary.find((x:any)=>x.encoding==='o200k_base'&&x.language==='zh').compactGrossPercent,-38.46);const selective=await (await fetch(url+'/api/research/selective')).json();assert.equal(selective.summary.length,20);assert.ok(selective.summary.every((x:any)=>x.netReductionPercent>90));const harness=await (await fetch(url+'/api/research/harness')).json();assert.equal(harness.results.length,2);assert.equal(harness.results[0].total.cases,1000);assert.ok(harness.results[0].total.veliqTotalReductionPercent<30);const status=await (await fetch(url+'/api/status')).json();assert.equal(status.metrics.length,2);const bad=await fetch(url+'/api/explore',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({text:'haz cualquier cosa'})});assert.equal(bad.status,400)}finally{server.close();store.close()}});
