import {spawnSync} from 'node:child_process';
import {ingestRun,listRuns} from '../../packages/metrics/benchmarks.ts';
import {resolve} from 'node:path';
import {existsSync,mkdirSync,writeFileSync,readFileSync} from 'node:fs';
import {parse,print} from '../../packages/language/parser.ts';
import {parseCompact,printCompact} from '../../packages/language/compact.ts';
import {parseC2,printC2} from '../../packages/language/compact2.ts';
import {parseC3,printC3} from '../../packages/language/compact3.ts';
import {fromText,canonical,decode,diagnostic,fromNatural,toNatural,supportedLanguages,type SupportedLanguage} from '../../packages/semantic/vsr.ts';
import {MemoryStore,defaultScope} from '../../packages/memory/store.ts';
import {processMessage} from '../../packages/runtime/runtime.ts';
import {startServer} from '../gateway/server.ts';
import {observationSummary} from '../../packages/metrics/observations.mjs';
import {nativeSummary} from '../../packages/runtime/native.mjs';
const args=process.argv.slice(2),cmd=args.shift()??'help';
const home=resolve(process.env.VELIQ_HOME??'.veliq');
const dbPath=resolve(home,'veliq.sqlite');
function store(){return new MemoryStore(dbPath)}
function output(x:unknown){console.log(typeof x==='string'?x:JSON.stringify(x,null,2))}
async function main(){
  switch(cmd){
    case 'init':mkdirSync(home,{recursive:true});if(!existsSync(resolve(home,'config.json')))writeFileSync(resolve(home,'config.json'),JSON.stringify({mode:'observe',privacy:'local'},null,2));store().close();output(`Inicializado: ${home}`);break;
    case 'doctor':{const detect=(name:string)=>{const r=spawnSync(name,['--version'],{encoding:'utf8',timeout:2000});return r.status===0?(r.stdout||r.stderr).trim():null};output({node:process.versions.node,nodeCompatible:Number(process.versions.node.split('.')[0])>=24,database:existsSync(dbPath),opencode:detect('opencode'),codex:detect('codex'),claude:detect('claude'),opencodeProjectConfig:existsSync(resolve('opencode.json')),mcpCommand:'node --experimental-strip-types apps/cli/main.ts mcp',externalRequests:false});break}
    case 'encode':{const language=args[0]==='--lang' ? args.splice(0,2)[1] : 'es';const surface=args[0]==='--compact'?(args.shift(),'compact'):args[0]==='--c2'?(args.shift(),'c2'):args[0]==='--c3'?(args.shift(),'c3'):'formal';if(language!=='veliq'&&!supportedLanguages.includes(language as SupportedLanguage))throw new Error('Idioma no soportado');const input=args.join(' ');if(!input)throw new Error('Falta texto');const v=language==='veliq'?fromText(input):fromNatural(input,language as SupportedLanguage);output({text:surface==='c3'?printC3(v.root):surface==='c2'?printC2(v.root):surface==='compact'?printCompact(v.root):print(v.root),vsr:JSON.parse(canonical(v))});break}
    case 'decode':{const surface=args[0]==='--compact'?(args.shift(),'compact'):args[0]==='--c2'?(args.shift(),'c2'):args[0]==='--c3'?(args.shift(),'c3'):'formal';const input=args.join(' ');const v=input.startsWith('{')?decode(input):fromText(surface==='c3'?print(parseC3(input)):surface==='c2'?print(parseC2(input)):surface==='compact'?print(parseCompact(input)):input);output({natural:toNatural(v),diagnostic:diagnostic(v)});break}
    case 'status':{const s=store();output({observations:observationSummary(process.cwd()),native:nativeSummary(process.cwd()),metrics:s.metrics().slice(0,10),memory:s.retrieve(defaultScope)});s.close();break}
    case 'context':{const sub=args.shift(),file=args.shift();if(!file)throw Error('Uso: veliq context put|select|sync|apply archivo.json');const data=JSON.parse(readFileSync(resolve(file),'utf8')),s=store();try{const c=await import('../../packages/memory/context.ts');if(sub==='put')output(c.putContext(s,data.input,data.expectedVersion));else if(sub==='select')output(c.selectContext(c.getContext(s,data.id,data.scope),data.query??'',data.maxBytes));else if(sub==='sync')output(c.prepareContext(s,data.id,data.scope,data.receiverDigest));else if(sub==='apply')output(c.applyContext(s,data.packet,data.authorizedScope));else throw Error('Operación de contexto desconocida')}finally{s.close()}break}
    case 'native':{const sub=args.shift();const {privateWrite,nativeConfigSchema}=await import('../../packages/runtime/install.ts');if(sub==='configure'){const file=args.shift();if(!file)throw Error('Uso: veliq native configure config.json');output({saved:privateWrite(process.cwd(),'native.json',nativeConfigSchema.parse(JSON.parse(readFileSync(resolve(file),'utf8'))),existsSync(resolve('.veliq/native.json')))})}else if(sub==='approve'){const file=args.shift();if(!file)throw Error('Uso: veliq native approve informe-pareado.json');const {approvePairedReport}=await import('../../packages/metrics/paired.ts');output({saved:approvePairedReport(process.cwd(),JSON.parse(readFileSync(resolve(file),'utf8'))),mode:'Configurar hybrid explícitamente para activar'})}else if(sub==='status')output(nativeSummary(process.cwd()));else throw Error('Uso: veliq native configure|approve|status');break}
    case 'benchmark':{if(args[0]==='--multilingual'||args[0]==='--selective'||args[0]==='--harness'){const flag=args.shift(),script=flag==='--selective'?'selective.py':flag==='--harness'?'harness.py':'multilingual.py';const supplied=flag==='--harness'&&args[0]?resolve(args[0]):undefined;const result=spawnSync('python3',[`research/benchmarks/${script}`,...(supplied?[supplied]:[])],{cwd:resolve(import.meta.dirname,'../..'),encoding:'utf8',timeout:30_000,maxBuffer:5_000_000});if(result.status!==0)throw new Error(result.stderr||'Instalá research/benchmarks/requirements.txt');output(JSON.parse(result.stdout));break}const {runBenchmark}=await import('../../research/benchmarks/run.ts');output(runBenchmark());break}
    case 'bench':{const sub=args.shift();if(sub==='paired'){const file=args.shift();if(!file)throw Error('Uso: veliq bench paired manifest.json --allow-external --output informe.json');const at=args.indexOf('--output'),target=at>=0?args[at+1]:undefined;if(!target)throw Error('--output obligatorio');const {runPaired}=await import('../../packages/metrics/paired.ts');const report=await runPaired(JSON.parse(readFileSync(resolve(file),'utf8')),args.includes('--allow-external'),undefined,message=>console.error(message));writeFileSync(resolve(target),JSON.stringify(report,null,2)+'\n',{flag:'wx',mode:0o600});output({report:resolve(target),summary:report.summary});break}const s=store();try{if(sub==='import'){const file=args.shift();if(!file)throw new Error('Uso: veliq bench import archivo.json');output(ingestRun(s,JSON.parse(readFileSync(resolve(file),'utf8'))))}else if(sub==='list')output(listRuns(s));else throw new Error('Uso: veliq bench paired|import|list')}finally{s.close()}break}
    case 'mcp':{const {serveVeliqMcp}=await import('../../adapters/mcp/server.ts');await serveVeliqMcp();break}
    case 'tui':{const s=store();try{const {runTui}=await import('./tui.ts');await runTui(s)}finally{s.close()}break}
    case 'dashboard':{const s=store();const server=startServer(s,Number(process.env.VELIQ_PORT??4173));await new Promise<void>(resolve=>server.on('listening',resolve));console.log(`VELIQ Studio local: http://127.0.0.1:${(server.address() as {port:number}).port}`);break}
    case 'install':case 'uninstall':{if(['codex','codex-observe','claude','claude-observe','claude-native'].includes(args[0])){const {installHookObserver,uninstallHookObserver}=await import('../../adapters/hooks/config.ts');const harness=args[0].startsWith('codex')?'codex':'claude-code',native=args[0]==='claude'||args[0]==='claude-native';output(cmd==='install'?installHookObserver(harness,process.cwd(),native):uninstallHookObserver(harness,process.cwd(),native));break}if(!['opencode','opencode-mcp','opencode-native','opencode-observe'].includes(args[0]))throw new Error('Uso: veliq install|uninstall opencode|opencode-native|opencode-mcp|opencode-observe|codex|claude');const {connectOpenCode,disconnectOpenCode,installOpenCodeObserver,uninstallOpenCodeObserver}=await import('../../adapters/opencode/config.ts');const {installOpenCodeNative,uninstallOpenCodeNative}=await import('../../packages/runtime/install.ts');if(args[0]==='opencode'){if(cmd==='install'){const mcp=connectOpenCode();try{output({mcp,native:installOpenCodeNative()})}catch(e){disconnectOpenCode();throw e}}else output({native:uninstallOpenCodeNative(),mcp:disconnectOpenCode()})}else output(args[0]==='opencode-observe'?(cmd==='install'?installOpenCodeObserver():uninstallOpenCodeObserver()):args[0]==='opencode-native'?(cmd==='install'?installOpenCodeNative():uninstallOpenCodeNative()):(cmd==='install'?connectOpenCode():disconnectOpenCode()));break}
    default:output('veliq init | doctor | status | encode [--lang ID] [--compact|--c2|--c3] TEXTO | decode [--c3] VELIQ | benchmark [--multilingual|--selective|--harness] | bench paired MANIFEST --allow-external --output REPORT | bench import|list | native configure|approve|status | context put|select|sync|apply FILE | mcp | tui | dashboard | install|uninstall opencode|opencode-native|opencode-mcp|opencode-observe|codex|claude');
  }
}
main().catch(e=>{console.error(`Error: ${e instanceof Error?e.message:String(e)}`);process.exitCode=1});
