import {McpServer} from '@modelcontextprotocol/sdk/server/mcp.js';
import {StdioServerTransport} from '@modelcontextprotocol/sdk/server/stdio.js';
import {z} from 'zod';
import {resolve} from 'node:path';
import {spawnSync} from 'node:child_process';
import {MemoryStore,defaultScope} from '../../packages/memory/store.ts';
import {fromNatural,fromText,canonical,decode,toNatural,diagnostic,supportedLanguages} from '../../packages/semantic/vsr.ts';
import {print} from '../../packages/language/parser.ts';
import {printCompact,parseCompact} from '../../packages/language/compact.ts';
import {ByteTokenizer,optimize,netPercent} from '../../packages/codec/optimizer.ts';
import {ingestRun,listRuns} from '../../packages/metrics/benchmarks.ts';
import {runBenchmark} from '../../research/benchmarks/run.ts';
const scope=z.object({user:z.string().min(1).max(128),workspace:z.string().min(1).max(128),project:z.string().min(1).max(128),session:z.string().min(1).max(128),agent:z.string().min(1).max(128)}).strict();
const answer=(data:unknown)=>({content:[{type:'text' as const,text:JSON.stringify(data)}],structuredContent:typeof data==='object'&&data!==null&&!Array.isArray(data)?data as Record<string,unknown>:{value:data}});
const error=(e:unknown)=>({content:[{type:'text' as const,text:e instanceof Error?e.message:String(e)}],isError:true});
const safe=async(fn:()=>unknown)=>{try{return answer(await fn())}catch(e){return error(e)}};
/** Construye herramientas sin depender de un cliente o harness específico. */
export function createVeliqMcp(store:MemoryStore){const server=new McpServer({name:'veliq',version:'0.1.0-alpha.4'});
  server.registerTool('veliq.capabilities',{description:'Capacidades reales y límites de VELIQ 0.1',inputSchema:{}},async()=>answer({language:'0.1',protocol:'0.1',translation:'una plantilla controlada en 10 idiomas o VELIQ formal',languages:supportedLanguages,tokenizer:'UTF-8 bytes en MCP; benchmark offline con tiktoken oficial',memory:'SQLite local por ámbito',benchmark:'corridas externas autodeclaradas',mode:'observe; hybrid sólo como propuesta no enviada al modelo'}));
  server.registerTool('veliq.encode',{description:'Traduce una plantilla controlada de idioma declarado o expresión formal a VSR y VELIQ.',inputSchema:{text:z.string().min(1).max(100_000),format:z.enum(['natural','spanish','veliq']).default('natural'),language:z.enum(supportedLanguages).default('es'),surface:z.enum(['formal','compact']).default('formal')}},async({text,format,language,surface})=>safe(()=>{const v=format==='veliq'?fromText(text):fromNatural(text,format==='spanish'?'es':language);return {text:surface==='compact'?printCompact(v.root):print(v.root),vsr:JSON.parse(canonical(v)),natural:toNatural(v)}}));
  server.registerTool('veliq.decode',{description:'Decodifica VELIQ formal, perfil C1 o VSR JSON; sólo recupera texto original verificado.',inputSchema:{text:z.string().min(1).max(100_000),format:z.enum(['veliq','compact','vsr']).default('veliq')}},async({text,format})=>safe(()=>{const v=format==='vsr'?decode(text):fromText(format==='compact'?print(parseCompact(text)):text);return {natural:toNatural(v),diagnostic:diagnostic(v),veliq:print(v.root)}}));
  server.registerTool('veliq.validate',{description:'Valida sintaxis, tipos y, opcionalmente, referencias conocidas.',inputSchema:{text:z.string().min(1).max(100_000),knownReferences:z.array(z.string().max(512)).max(1000).optional()}},async({text,knownReferences})=>safe(()=>{const v=fromText(text,undefined,knownReferences?new Set(knownReferences):undefined);return {valid:true,canonical:print(v.root)}}));
  server.registerTool('veliq.optimize',{description:'Analiza plantilla controlada; Observe nunca altera la entrada. Conteos de bytes, no tokens del proveedor.',inputSchema:{text:z.string().min(1).max(100_000),language:z.enum(supportedLanguages).default('es'),mode:z.enum(['observe','hybrid']).default('observe')}},async({text,language,mode})=>safe(()=>{let v;try{v=fromNatural(text,language)}catch{}const decision=optimize(text,v,new ByteTokenizer(),mode,'VELIQ dictionary 0.1');store.metric({mode,strategy:decision.strategy,original:decision.original.value,optimized:decision.optimized.value,overhead:decision.overhead.value,kind:decision.original.kind,fallback:decision.fallback});return {...decision,netPercent:netPercent(decision)}}));
  server.registerTool('veliq.memory.store',{description:'Guarda un recuerdo local en el ámbito explícito; versión anterior opcional para prevenir conflictos. No guardar secretos.',inputSchema:{id:z.string().min(1).max(256),scope,kind:z.enum(['episodic','semantic','project','operational','decision','error','preference','reference']),body:z.string().max(100_000),provenance:z.string().min(1).max(256),expectedVersion:z.number().int().nonnegative().optional()}},async({id,scope,kind,body,provenance,expectedVersion})=>safe(()=>store.put(id,scope,kind,body,provenance,expectedVersion)));
  server.registerTool('veliq.memory.retrieve',{description:'Recupera recuerdos sólo del ámbito exacto indicado; sin mezclar proyectos.',inputSchema:{scope,query:z.string().max(256).default(''),limit:z.number().int().min(1).max(50).default(20)}},async({scope,query,limit})=>safe(()=>store.retrieve(scope,query,limit).map(row=>({...row,body:store.getContent(String(row.hash))}))));
  server.registerTool('veliq.benchmark',{description:'Ejecuta benchmark local de bytes, benchmark offline multilingüe de tokens de texto, o ingesta corrida externa. Python tiktoken es dependencia opcional.',inputSchema:{action:z.enum(['synthetic','multilingual','list','ingest']),run:z.record(z.unknown()).optional()}},async({action,run})=>safe(()=>{if(action==='synthetic')return runBenchmark();if(action==='multilingual'){const result=spawnSync('python3',['research/benchmarks/multilingual.py'],{cwd:resolve(import.meta.dirname,'../..'),encoding:'utf8',timeout:30_000,maxBuffer:5_000_000});if(result.status!==0)throw new Error(`Benchmark multilingüe no disponible: ${result.stderr||'instalá research/benchmarks/requirements.txt'}`);return JSON.parse(result.stdout)}if(action==='list')return {runs:listRuns(store)};if(!run)throw new Error('run obligatorio');return ingestRun(store,run)}));
  return server;
}
export async function serveVeliqMcp(path=resolve(process.env.VELIQ_HOME??'.veliq','veliq.sqlite')){const store=new MemoryStore(path);const server=createVeliqMcp(store);const transport=new StdioServerTransport();try{await server.connect(transport)}catch(e){store.close();throw e}process.once('exit',()=>store.close());return server}
